mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.home, name='home'),
    path('academics', views.academics, name='academics'),
    path('professional', views.professional, name='professional'),

    path('blog', views.blog, name='blog'),
    path('my-blog/<int:id>', views.my_blog, name='my-blog'),
    path('blog-detail/<int:id>', views.blog_detail, name='blog-detail'),
    path('portfolio-detail/<int:id>', views.portfolio_detail, name='portfolio-detail'),
    path('web-services', views.web_services, name='web-services'),
    path('mobile-services', views.mobile_services, name='mobile-services'),
    path('desktop-services', views.desktop_services, name='desktop-services'),

    path('feedback', views.feedback, name='feedback'),

]

mysite/portfolio/models.py
from django.db import models


class Portfolio(models.Model):
    CATEGORY_CHOICES = [
        ('Web design', 'Web design'),
        ('Other', 'Other'),
    ]
    title = models.CharField(max_length=25)
    img = models.ImageField(upload_to='pics')
    support_img_1 = models.ImageField(upload_to='pics/support-1')
    support_img_2 = models.ImageField(upload_to='pics/support-2')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='Web design')
    client = models.CharField(max_length=100, default='After Nepal')
    project_date = models.DateField()
    project_url = models.URLField(default="")
    description = models.TextField()

    def __str__(self):
        return f"{self.category} - {self.client} - {self.project_date}"

class Blog_Category(models.Model):
    category = models.CharField(max_length=20)
    img = models.ImageField(upload_to='blogs-category')

    def __str__(self):
        return self.category


class Blog(models.Model):
    blog = models.ForeignKey(Blog_Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=25)
    description = models.TextField()
    imp_description = models.TextField()
    img = models.ImageField(upload_to='my-blog')


    def __str__(self):
        return self.title


class Web_Services(models.Model):
    icon = models.CharField(max_length=220)
    web_service_heading = models.CharField(max_length=50)
    description1 = models.TextField()
    description2 = models.TextField()
    description3 = models.TextField()
    description4 = models.TextField()

    def __str__(self):
        return self.web_service_heading


class Mobile_Services(models.Model):
    icon = models.CharField(max_length=220)
    mobile_service_heading = models.CharField(max_length=50)
    description1 = models.TextField()
    description2 = models.TextField()
    description3 = models.TextField()
    description4 = models.TextField()

    def __str__(self):
        return self.mobile_service_heading

class Desktop_Services(models.Model):
    icon = models.CharField(max_length=220)
    desktop_service_heading = models.CharField(max_length=50)
    description1 = models.TextField()
    description2 = models.TextField()
    description3 = models.TextField()
    description4 = models.TextField()

    def __str__(self):
        return self.desktop_service_heading

class Feedback(models.Model):
    name = models.CharField(max_length=50, null=False)
    email = models.EmailField(null=False)
    subject = models.CharField(null=False)
    message = models.TextField()

    def __str__(self):
        return f'{self.name} -- {self.subject}'

mysite/portfolio/views.py
from django.shortcuts import render, redirect

from .models import Portfolio, Blog_Category, Blog, Web_Services, Feedback, Mobile_Services, Desktop_Services


# Create your views here.
def home(request):
    portfolios = Portfolio.objects.all()
    context = {"portfolios": portfolios}
    print(portfolios.values())
    return render(request, 'index.html', context)


def portfolio_detail(request, id):
    portfolio_detail = Portfolio.objects.get(id=id)

    context = {"portfolio_detail": portfolio_detail}
    return render(request, 'portfolio-detail.html', context)

def blog(request):
    latest_blog = Blog_Category.objects.all()
    context = {"latest_blog": latest_blog}
    print(context)
    return render(request, 'blog.html', context)

def my_blog(request, id):
    my_blog = Blog.objects.filter(blog_id = id)
    context = {"my_blog": my_blog}
    print(context)
    return render(request, 'my-blog.html', context)


def blog_detail(request, id):
    blog_detail = Blog.objects.get(id=id)
    context = {"blog_detail": blog_detail}
    print(context)
    return render(request, 'blog-detail.html', context)

def web_services(request):
    services = Web_Services.objects.all()
    print(services)
    context = {"services": services}
    return render(request, 'web_services.html', context)

def feedback(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        feedback1 = Feedback.objects.create(name = name, email = email, subject = subject, message = message)
        feedback1.save()
        return render(request, "success.html")
    else:
        redirect("/")

def mobile_services(request):
    services = Mobile_Services.objects.all()
    print(services)
    context = {"services": services}
    return render(request, 'mobile_services.html', context)

def desktop_services(request):
    services = Desktop_Services.objects.all()
    print(services)
    context = {"services": services}
    return render(request, 'desktop_services.html', context)


def academics(request):
    return render(request, 'academics.html')
def professional(request):
    return render(request, 'professional.html')

mysite/templates/academics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Coming Soon</h1>
</body>
</html>

mysite/templates/base.html
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
  {% block title %}
  {% endblock %}

  </title>
</head>
<body>

</body>
</html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
 <link href="{% static 'img/favicon.png' %}" rel="icon">
<link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
<link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

  {% block css %}

  {% endblock %}

  <!-- =======================================================
  * Template Name: DevFolio
  * Template URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top" style="background-color: black">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'portfolio:home'%}">Prakash Koirala</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="base.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about ">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#work">Work</a></li>
          <li><a class="nav-link scrollto " href="/blog">Blog</a></li>
          <li class="dropdown"><a href="#"><span>Achievements</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="academics">Academics</a></li>
              <li><a href="professional">Professional</a></li>
             
              <!-- <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li> -->
            </ul>
          </li>

          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
          <!-- <li><a class="nav-link scrollto" href="#contact">Gallery</a></li> -->

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->


  <!-- ======= Main Content ======= -->
  {% block content %}

  {% endblock %}


<!-- ======= Footer ======= -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="copyright-box">
            <p class="copyright">&copy; Copyright <strong>Wake And Tech Nepal</strong>. All Rights Reserved</p>
            <div class="credits">
              <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=DevFolio
            -->
              Designed by <a href="https://www.watnepal.com/">Wake And Tech Nepal</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% block javascript %}

  {% endblock %}


  <!-- Vendor JS Files -->
<script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

mysite/templates/blog-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


  <main id="main">

    <!-- ======= Blog Single Section ======= -->
    <section class="blog-wrapper sect-pt4" id="blog">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="post-box">
              <div class="post-thumb">
                <img src="{{blog_detail.img.url}}" class="img-fluid" alt="">
              </div>
              <div class="post-meta">
                <h1 class="article-title">Lorem ipsum dolor sit amet consec tetur adipisicing</h1>
                <ul>
                  <li>
                    <span class="bi bi-person"></span>
                    <a href="#">Jason London</a>
                  </li>
                  <li>
                    <span class="bi bi-tag"></span>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <span class="bi bi-chat-left-text"></span>
                    <a href="#">14</a>
                  </li>
                </ul>
              </div>
              <div class="article-content">
                <p>
                  Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Cras ultricies ligula sed magna dictum
                  porta. Quisque velit
                  nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque
                  nec, egestas non nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
                  cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
                  Nulla quis lorem ut libero malesuada feugiat.
                </p>
                <p>
                  Nulla porttitor accumsan tincidunt. Cras ultricies ligula sed magna dictum porta. Mauris blandit
                  aliquet elit, eget tincidunt
                  nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Lorem ipsum dolor sit amet,
                  consectetur adipiscing elit. Donec sollicitudin molestie malesuada.
                </p>
                <p>
                  Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Lorem ipsum dolor sit amet, consectetur
                  adipiscing elit. Praesent
                  sapien massa, convallis a pellentesque nec, egestas non nisi. Lorem ipsum dolor sit amet,
                  consectetur adipiscing elit. Curabitur arcu erat, accumsan id imperdiet et, porttitor at
                  sem. Donec rutrum congue leo eget malesuada.
                </p>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.
                  Curabitur arcu erat,
                  accumsan id imperdiet et, porttitor at sem. Vivamus suscipit tortor eget felis porttitor
                  volutpat. Vivamus suscipit tortor eget felis porttitor volutpat. Quisque velit nisi, pretium
                  ut lacinia in, elementum id enim.
                </p>
                <blockquote class="blockquote">
                  <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                </blockquote>
                <p>
                  Nulla porttitor accumsan tincidunt. Cras ultricies ligula sed magna dictum porta. Mauris blandit
                  aliquet elit, eget tincidunt
                  nibh pulvinar a. Cras ultricies ligula sed magna dictum porta. Lorem ipsum dolor sit amet,
                  consectetur adipiscing elit. Donec sollicitudin molestie malesuada.
                </p>
              </div>
            </div>
            <div class="box-comments">
              <div class="title-box-2">
                <h4 class="title-comments title-left">Comments (34)</h4>
              </div>
              <ul class="list-comments">
                <li>
                  <div class="comment-avatar">
                    <img src="assets/img/testimonial-2.jpg" alt="">
                  </div>
                  <div class="comment-details">
                    <h4 class="comment-author">Oliver Colmenares</h4>
                    <span>18 Sep 2017</span>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque
                      ipsam temporibus maiores
                      quae natus libero optio, at qui beatae ducimus placeat debitis voluptates amet corporis.
                    </p>
                    <a href="3">Reply</a>
                  </div>
                </li>
                <li>
                  <div class="comment-avatar">
                    <img src="assets/img/testimonial-4.jpg" alt="">
                  </div>
                  <div class="comment-details">
                    <h4 class="comment-author">Carmen Vegas</h4>
                    <span>18 Sep 2017</span>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque
                      ipsam temporibus maiores
                      quae natus libero optio, at qui beatae ducimus placeat debitis voluptates amet corporis,
                      veritatis deserunt.
                    </p>
                    <a href="3">Reply</a>
                  </div>
                </li>
                <li class="comment-children">
                  <div class="comment-avatar">
                    <img src="assets/img/testimonial-2.jpg" alt="">
                  </div>
                  <div class="comment-details">
                    <h4 class="comment-author">Oliver Colmenares</h4>
                    <span>18 Sep 2017</span>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque
                      ipsam temporibus maiores
                      quae.
                    </p>
                    <a href="3">Reply</a>
                  </div>
                </li>
                <li>
                  <div class="comment-avatar">
                    <img src="assets/img/testimonial-2.jpg" alt="">
                  </div>
                  <div class="comment-details">
                    <h4 class="comment-author">Oliver Colmenares</h4>
                    <span>18 Sep 2017</span>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque
                      ipsam temporibus maiores
                      quae natus libero optio.
                    </p>
                    <a href="3">Reply</a>
                  </div>
                </li>
              </ul>
            </div>
            <div class="form-comments">
              <div class="title-box-2">
                <h3 class="title-left">
                  Leave a Reply
                </h3>
              </div>
              <form class="form-mf">
                <div class="row">
                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <input type="text" class="form-control input-mf" id="inputName" placeholder="Name *" required>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <input type="email" class="form-control input-mf" id="inputEmail1" placeholder="Email *" required>
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <div class="form-group">
                      <input type="url" class="form-control input-mf" id="inputUrl" placeholder="Website">
                    </div>
                  </div>
                  <div class="col-md-12 mb-3">
                    <div class="form-group">
                      <textarea id="textMessage" class="form-control input-mf" placeholder="Comment *" name="message" cols="45" rows="8" required></textarea>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <button type="submit" class="button button-a button-big button-rouded">Send Message</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="col-md-4">
            <div class="widget-sidebar sidebar-search">
              <h5 class="sidebar-title">Search</h5>
              <div class="sidebar-content">
                <form>
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-secondary btn-search" type="button">
                        <span class="bi bi-search"></span>
                      </button>
                    </span>
                  </div>
                </form>
              </div>
            </div>
            <div class="widget-sidebar">
              <h5 class="sidebar-title">Recent Post</h5>
              <div class="sidebar-content">
                <ul class="list-sidebar">
                  <li>
                    <a href="#">Atque placeat maiores.</a>
                  </li>
                  <li>
                    <a href="#">Lorem ipsum dolor sit amet consectetur</a>
                  </li>
                  <li>
                    <a href="#">Nam quo autem exercitationem.</a>
                  </li>
                  <li>
                    <a href="#">Atque placeat maiores nam quo autem</a>
                  </li>
                  <li>
                    <a href="#">Nam quo autem exercitationem.</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="widget-sidebar">
              <h5 class="sidebar-title">Archives</h5>
              <div class="sidebar-content">
                <ul class="list-sidebar">
                  <li>
                    <a href="#">September, 2017.</a>
                  </li>
                  <li>
                    <a href="#">April, 2017.</a>
                  </li>
                  <li>
                    <a href="#">Nam quo autem exercitationem.</a>
                  </li>
                  <li>
                    <a href="#">Atque placeat maiores nam quo autem</a>
                  </li>
                  <li>
                    <a href="#">Nam quo autem exercitationem.</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="widget-sidebar widget-tags">
              <h5 class="sidebar-title">Tags</h5>
              <div class="sidebar-content">
                <ul>
                  <li>
                    <a href="#">Web.</a>
                  </li>
                  <li>
                    <a href="#">Design.</a>
                  </li>
                  <li>
                    <a href="#">Travel.</a>
                  </li>
                  <li>
                    <a href="#">Photoshop</a>
                  </li>
                  <li>
                    <a href="#">Corel Draw</a>
                  </li>
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->

{% endblock %}

mysite/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>

  body{
  margin-top: 20px;

  }
.blog-image{
height: 300px;
width: 100%;
border-radius: 10%;
}
.blog-category{
text-align: center;
}

</style>
{% endblock %}


{% block content %}
  {% if latest_blog %}
    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog-mf sect-pt4 route">
      <div class="container" style="margin-top: 50px">
        <div class="row">
          {% for blog in latest_blog %}
            <div class="col-sm-4" style="margin-bottom: 20px">
              <a href="{% url 'portfolio:my-blog' blog.id %}">
                <div class="item">
                  <img class="blog-image"  src="{{ blog.img.url }}" alt="Image" class="img-fluid">

                 <h3 class="blog-category">

                      {{ blog.category }}
                 </h3>

                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
  {% else %}
    <div class="container">
      <h1>No Blogs available</h1>
    </div>
  {% endif %}
{% endblock %}

mysite/templates/desktop_services.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
   .icon-100 { font-size: 100px; color: blue; }
    .icon-100:hover { color: black; }

</style>

{% endblock %}

{% block content %}

<div class="row" style="margin-top: 150px; margin-left: 50px; margin-right: 50px; ">
    {% for service in services %}
    <div class="col-md-4">
        <div class="service-box">
            <div class="service-ico">
                <i class="{{service.icon}} icon-100"></i>
            </div>
            <div class="service-content">
                <h2 class="s-title">{{service.desktop_service_heading}}</h2>
                <ol type="1">
                    <li style="text-align: left;">{{service.description1}}</li>
                    <li style="text-align: left;">{{service.description2}}</li>
                    <li style="text-align: left;">{{service.description3}}</li>
                    <li style="text-align: left;">{{service.description4}}</li>
                </ol>
            </div>
        </div>
    </div>
    {% endfor %}


</div>

{% endblock %}

mysite/templates/mobile_services.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
   .icon-100 { font-size: 100px; color: blue; }
    .icon-100:hover { color: black; }

</style>

{% endblock %}

{% block content %}

<div class="row" style="margin-top: 150px; margin-left: 50px; margin-right: 50px; ">
    {% for service in services %}
    <div class="col-md-4">
        <div class="service-box">
            <div class="service-ico">
                <i class="{{service.icon}} icon-100"></i>
            </div>
            <div class="service-content">
                <h2 class="s-title">{{service.mobile_service_heading}}</h2>
                <ol type="1">
                    <li style="text-align: left;">{{service.description1}}</li>
                    <li style="text-align: left;">{{service.description2}}</li>
                    <li style="text-align: left;">{{service.description3}}</li>
                    <li style="text-align: left;">{{service.description4}}</li>
                </ol>
            </div>
        </div>
    </div>
    {% endfor %}


</div>

{% endblock %}

mysite/templates/my-blog.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
<div class="row" style="margin-top: 100px; padding-left: 100px; padding-right: 100px">

    {% for blog in my_blog %}


    <div class="col-sm-4"  >
        <div class="card card-blog">
            <div class="card-img">
                <a href="{% url 'portfolio:blog-detail' blog.id %}">
                    <img src="{{ blog.img.url }}" alt="" class="img-fluid image-hover"
                         style="height: 250px; border-radius: 10%">
                </a>
            </div>
            <div class="card-body">
                <div class="card-category-box">
                    <div class="card-category">
                        <h6 class="category">{{blog.title}}</h6>
                    </div>
                </div>
                <h3 class="card-title"><a href="blog-single.html">{{blog.description}}</a></h3>
                <p class="card-description">
                    {{ blog.imp_description|truncatewords:40 }}
                </p>

            </div>

        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mysite/templates/portfolio-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


  <main id="main" style="margin-top: 100px">

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img style="height: 500px; width: 500px" src="{{portfolio_detail.img.url}}" alt="">
                </div>

                <div class="swiper-slide">
                  <img style="height: 500px; width: 500px" src="{{portfolio_detail.support_img_1.url}}" alt="">
                </div>

                <div class="swiper-slide">
                  <img style="height: 500px; width: 500px" src="{{portfolio_detail.support_img_2.url}}" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Project information</h3>

              <ul>
                <li><strong>Category</strong>: {{portfolio_detail.category}}</li>
                <li><strong>Client</strong>: {{portfolio_detail.client}}</li>
                <li><strong>Project date</strong>: {{portfolio_detail.project_date}}</li>
                <li><strong>Project URL</strong>: <a href="{{portfolio_detail.project_url}}">{{portfolio_detail.project_url}}</a></li>
              </ul>
            </div>
            <div class="portfolio-description" style="height: auto">
              <h2>Portfolio Detail</h2>

             <p style="text-align: justify"> {{portfolio_detail.description}} </p>

            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->
  </main>

{% endblock %}

mysite/templates/professional.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Coming Soon</h1>
</body>
</html>

mysite/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Message Submitted Succesively</h1>

<a href="/"><button>Home</button></a>
</body>
</html>

mysite/templates/web_services.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
   .icon-100 { font-size: 100px; color: blue; }
    .icon-100:hover { color: black; }

</style>

{% endblock %}

{% block content %}

<div class="row" style="margin-top: 150px; margin-left: 50px; margin-right: 50px; ">
    {% for service in services %}
    <div class="col-md-4">
        <div class="service-box">
            <div class="service-ico">
                <i class="{{service.icon}} icon-100"></i>
            </div>
            <div class="service-content">
                <h2 class="s-title">{{service.web_service_heading}}</h2>
                <ol type="1">
                    <li style="text-align: left;">{{service.description1}}</li>
                    <li style="text-align: left;">{{service.description2}}</li>
                    <li style="text-align: left;">{{service.description3}}</li>
                    <li style="text-align: left;">{{service.description4}}</li>
                </ol>
            </div>
        </div>
    </div>
    {% endfor %}


</div>

{% endblock %}